#!/bin/bash

. /etc/rc.defaults
. /etc/rc.subr/extractbootparams
msg="The free Gnash plugin (Adobe Flash replacement) is enabled now. Please restart Firefox"'!'
act="Gnash is already active. No restart of Firefox required"'!'
[ "$lang" = "de" ] && \
	msg="Das freie Gnash-Plugin (Adobe Flash Ersatz) ist nun aktiv. Bitte starten Sie Firefox neu"'!' && \
	act="Gnash ist bereits aktiv. Kein Neustart von Firefox erforderlich"'!'
[ "$lang" = "pl" ] && \
	msg="Wtyczka Gnash jest teraz aktywna. Zrestartuj Firefoksa." && \
	act="Wtyczka Gnash jest już aktywna. Nie trzeba restartować Firefoksa."

if [ -L /opt/firefox35/lib/firefox/plugins/libgnashplugin.so ] ; then
	zenity --info --text "$act"
else
	rm /opt/firefox35/lib/firefox/plugins/libflashplayer.so
	ln -sf /usr/lib/browserplugins/libgnashplugin.so /opt/firefox35/lib/firefox/plugins/libgnashplugin.so
	echo -n libgnashplugin.so > /etc/lesslinux/flashplugin
	zenity --info --text "$msg"
fi
