#!/bin/bash
	
PATH=/usr/bin:/usr/sbin:/bin:/sbin:/static/bin:/static/sbin
export PATH
HOME=/root
export HOME
mkdir -p -m 0600 /home 

. /etc/rc.defaults
. /etc/rc.subr/extractbootparams
. /etc/rc.subr/colors
. /etc/lesslinux/branding/branding.en.sh
[ -f "/etc/default/windowmanager" ] && . /etc/default/windowmanager
[ -f "/etc/lesslinux/branding/branding.${lang}.sh" ] && . /etc/lesslinux/branding/branding.${lang}.sh
[ -n "$xorgconf" ] && export xorgconf
[ -n "$xorgscreen" ] && export xorgscreen

for i in /etc/xinitrc.d/[0-9][0-9][0-9][0-9]-*.?? ; do
	provides="` cat $i | grep '#lesslinux provides' | awk '{print $3}' `"
	if echo "$skipservices" | grep -q '|'$provides'|' ; then
		echo "Skipping $provides"
	else
		$i start
	fi
done

# Set DPI value 
if [ -f /root/.lesslinux/xstuff.xrdb ] ; then
	xrdb -load /root/.lesslinux/xstuff.xrdb
else
	mkdir -p /root/.lesslinux
	echo "Xft.dpi: ${dpi}" >> /root/.lesslinux/xstuff.xrdb
	xrdb -load /root/.lesslinux/xstuff.xrdb
fi

#mkdir -p /root/.config
#mkdir -p /root/.icewm
#mount -t tmpfs -o mode=0755 tmpfs /root/.config
#mount -t tmpfs -o mode=0755 tmpfs /root/.icewm
#rsync -avHP /home/surfer/.icewm/ /root/.icewm/
#rsync -avHP /home/surfer/.config/ /root/.config/
# FIXME: Do not hardcode theme here!
#tar -C /usr/share/themes/Adwaita -cvf - gtk-3.0 gtk-2.0 | tar -C /root/.config -xf -
#chown -R root:root /root/.icewm/ 
#chown -R root:root /root/.config/

if [ "$lang" = "ru" ] ; then
	setxkbmap -layout us,ru -variant ,winkeys -option grp:alt_shift_toggle,grp_led:scroll
else
	setxkbmap -layout "$xkbmap"
fi

if xdpyinfo | grep -q -i composite ; then
	compton --shadow-exclude '_GTK_FRAME_EXTENTS@:c' --fade-exclude '_GTK_FRAME_EXTENTS@:c' -cCGbf 
	xcompmgr -c &
fi

if  [ -n "$xrandr" ] ; then
	/usr/bin/xrandr --size "$xrandr"
fi

# Terminal &

/usr/bin/Esetroot -scale /etc/lesslinux/branding/desktop.png
if [ "$RUNTIMECONFWM" = "icewm" ] ; then
	echo 'ShowTaskBar=0' >> /root/.icewm/preferences 
	icewm &
	/usr/bin/Esetroot -scale /etc/lesslinux/branding/desktop.jpg
else
	/usr/bin/matchbox-window-manager -force_dialogs "Startup: $brandlong" &
fi

xfsettingsd 
( for n in ` seq 5 ` ; do
	sleep 1
	xfsettingsd --replace 
done ) &

/usr/bin/ruby /usr/local/xconfgui/runtimeconf.rb
#umount /root/.config
#umount /root/.icewm
#umount -f /root/.config
#umount -f /root/.icewm
