#!/bin/bash
	
PATH=/usr/bin:/usr/sbin:/bin:/sbin:/static/bin:/static/sbin
export PATH
HOME=/root
export HOME
mkdir -p -m 0600 /home 

. /etc/rc.defaults
. /etc/rc.subr/extractbootparams
. /etc/rc.subr/colors
. /etc/lesslinux/branding/branding.en.sh
[ -f "/etc/default/windowmanager" ] && . /etc/default/windowmanager
[ -f "/etc/lesslinux/branding/branding.${lang}.sh" ] && . /etc/lesslinux/branding/branding.${lang}.sh
[ -n "$xorgconf" ] && export xorgconf
[ -n "$xorgscreen" ] && export xorgscreen

/etc/xinitrc.d/0005-xrandr.sh start
/etc/xinitrc.d/0020-xrdb.sh start

if [ "$xkbmap" = "ru" ] ; then
	setxkbmap -layout us,ru -variant ,winkeys -option grp:alt_shift_toggle,grp_led:scroll
else
	setxkbmap -layout "$xkbmap"
fi
 
if [ "$RUNTIMECONFWM" = "icewm" ] ; then
	echo 'ShowTaskBar=0' >> /root/.icewm/preferences 
	icewm &
	/usr/bin/Esetroot -scale /etc/lesslinux/branding/desktop.jpg
else
	/usr/bin/matchbox-window-manager -force_dialogs "Startup: $brandlong,Select your language,Warnung" &
fi

for i in /etc/xinitrc.d/[0-9][0-9][0-9][0-9]-*.?? ; do
	provides="` cat $i | grep '#lesslinux provides' | awk '{print $3}' `"
	if echo "$skipservices" | grep -q '|'$provides'|' ; then
		echo "Skipping $provides"
	else
		$i start
		. /etc/rc.subr/extractbootparams
	fi
done

/usr/bin/ruby /usr/local/xconfgui/runtimeconf.rb
