#!/bin/bash
	
PATH=/usr/bin:/usr/sbin:/bin:/sbin:/static/bin:/static/sbin
export PATH
HOME=/root
export HOME
mkdir -p -m 0600 /home 

. /etc/rc.defaults
. /etc/rc.subr/extractbootparams
. /etc/rc.subr/colors
. /etc/lesslinux/branding/branding.en.sh
[ -f "/etc/default/windowmanager" ] && . /etc/default/windowmanager
[ -f "/etc/lesslinux/branding/branding.${lang}.sh" ] && . /etc/lesslinux/branding/branding.${lang}.sh
[ -n "$xorgconf" ] && export xorgconf
[ -n "$xorgscreen" ] && export xorgscreen

for i in /etc/xinitrc.d/[0-9][0-9][0-9][0-9]-*.?? ; do
	provides="` cat $i | grep '#lesslinux provides' | awk '{print $3}' `"
	if echo "$skipservices" | grep -q '|'$provides'|' ; then
		echo "Skipping $provides"
	else
		$i start
	fi
done

# Set DPI value 
if [ -f /root/.lesslinux/xstuff.xrdb ] ; then
	xrdb -load /root/.lesslinux/xstuff.xrdb
else
	mkdir -p /root/.lesslinux
	echo "Xft.dpi: ${dpi}" >> /root/.lesslinux/xstuff.xrdb
	xrdb -load /root/.lesslinux/xstuff.xrdb
fi

if [ "$xkbmap" = "ru" ] ; then
	setxkbmap -layout us,ru -variant ,winkeys -option grp:alt_shift_toggle,grp_led:scroll
else
	setxkbmap -layout "$xkbmap"
fi

if xdpyinfo | grep -q -i composite ; then
	compton --shadow-exclude '_GTK_FRAME_EXTENTS@:c' --fade-exclude '_GTK_FRAME_EXTENTS@:c' -cCGbf 
	xcompmgr -c &
fi

if  [ -n "$xrandr" ] ; then
	/usr/bin/xrandr --size "$xrandr"
fi

# Terminal &

/usr/bin/Esetroot -scale /etc/lesslinux/branding/desktop.png
if [ "$RUNTIMECONFWM" = "icewm" ] ; then
	echo 'ShowTaskBar=0' >> /root/.icewm/preferences 
	icewm &
	/usr/bin/Esetroot -scale /etc/lesslinux/branding/desktop.jpg
else
	/usr/bin/matchbox-window-manager -force_dialogs "Startup: $brandlong,Select your language" &
fi

xfsettingsd 
( for n in ` seq 5 ` ; do
	sleep 1
	xfsettingsd --replace 
done ) &

if [ "$nolangsel" -gt 0 -o -n "$xlocale" ] ; then
	echo "Skipping language selection"
else
	/usr/bin/ruby -I /usr/share/lesslinux/drivetools /usr/local/xconfgui/langselect.rb
	. /etc/rc.subr/extractbootparams
	if [ "$xkbmap" = "ru" ] ; then
		setxkbmap -layout us,ru -variant ,winkeys -option grp:alt_shift_toggle,grp_led:scroll
	else
		setxkbmap -layout "$xkbmap"
	fi
fi

/usr/bin/ruby /usr/local/xconfgui/runtimeconf.rb
